// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PopupMenuScssNamespace {
  export interface IPopupMenuScss {
    item: string;
    menu: string;
    scrim: string;
  }
}

declare const PopupMenuScssModule: PopupMenuScssNamespace.IPopupMenuScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: PopupMenuScssNamespace.IPopupMenuScss;
};

export = PopupMenuScssModule;
