import { join } from "path";
import { FirebaseError } from "../error";
import { hostingConfig } from "../hosting/config";
import { discover } from "./index";
import { confirm } from "../prompt";
import { logLabeledBullet, logLabeledWarning, logLabeledSuccess } from "../utils";
import {
  doSetupSourceDeploy,
  ensureAppHostingComputeServiceAccount,
  ensureRequiredApisEnabled,
} from "../apphosting/backend";
import { listBackends, ensureApiEnabled } from "../gcp/apphosting";
import { needProjectId } from "../projectUtils";
import * as fs from "fs-extra";
import * as experiments from "../experiments";
import * as clc from "colorette";

/**
 *
 */
export async function handleWebFrameworkMigration(
  targetNames: string[],
  context: any,
  options: any,
): Promise<void> {
  const projectId = needProjectId(options);
  const projectRoot = options.projectRoot || ".";
  const configs = hostingConfig(options);

  if (configs.length === 0) {
    return;
  }

  const updatedConfigs: any[] = [];
  let hasSsrMigration = false;

  for (const config of configs) {
    const { source, site } = config;
    if (!source) {
      updatedConfigs.push(config);
      continue;
    }

    // We have a legacy web framework config!
    const getProjectPath = () => join(projectRoot, source);
    const results = await discover(getProjectPath(), /* warn= */ false);

    if (!results) {
      logLabeledWarning(
        "hosting",
        `Legacy web framework config detected with source "${source}" but could not auto-detect framework. Proceeding with legacy deploy.`,
      );
      updatedConfigs.push(config);
      continue;
    }

    const { framework, mayWantBackend } = results;

    if (mayWantBackend) {
      // SSR Meta-framework
      logLabeledBullet(
        "hosting",
        `Detected SSR framework: ${clc.bold(framework)}. Legacy 'webframeworks' experiment is deprecated for SSR apps.`,
      );

      if (options.nonInteractive) {
        throw new FirebaseError(
          `Legacy 'webframeworks' experiment is deprecated. Please migrate your project to Firebase App Hosting manually, or run without --non-interactive for assistance.`,
        );
      }

      const confirmSsr = await confirm({
        message: `Would you like to migrate site "${site}" to Firebase App Hosting?`,
        default: true,
      });

      if (!confirmSsr) {
        logLabeledWarning(
          "hosting",
          "Continuing with legacy deployment (deprecated). We strongly recommend migrating to App Hosting.",
        );
        updatedConfigs.push(config);
        continue;
      }

      hasSsrMigration = true;

      // Step 1: Interactively check/create App Hosting backend
      const backendId = site
        .toLowerCase()
        .replace(/[^a-z0-9-]/g, "-")
        .substring(0, 30);
      logLabeledBullet("apphosting", `Checking for existing App Hosting backend "${backendId}"...`);

      // Ensure required APIs are enabled
      await ensureApiEnabled(options);
      await ensureRequiredApisEnabled(projectId);
      await ensureAppHostingComputeServiceAccount(projectId, "");

      const { backends } = await listBackends(projectId, "-");
      const backendExists = backends.some((b: any) => b.name.split("/").pop() === backendId);

      if (!backendExists) {
        logLabeledBullet(
          "apphosting",
          `App Hosting backend "${backendId}" does not exist. Creating one now...`,
        );
        await doSetupSourceDeploy(projectId, backendId);
      } else {
        logLabeledSuccess("apphosting", `Found existing App Hosting backend "${backendId}".`);
      }

      // Step 2: Update firebase.json
      // Add the apphosting block
      const apphostingConfig = {
        backendId,
        localBuild: true,
      };
      options.config.set("apphosting", apphostingConfig);

      // Remove source and framework-specific fields from the hosting block
      const newHostingConfig = { ...config };
      delete newHostingConfig.source;
      delete newHostingConfig.frameworksBackend;
      // Make sure it points to static public folder generated by app hosting builds
      newHostingConfig.public = `.apphosting/public`; // Universal Maker / local build target
      updatedConfigs.push(newHostingConfig);

      // Step 3: Prompt manual changes
      // Check if headers, redirects, rewrites exist in config
      const hasManualRules =
        (config.headers && config.headers.length > 0) ||
        (config.redirects && config.redirects.length > 0) ||
        (config.rewrites && config.rewrites.length > 0);

      if (hasManualRules) {
        logLabeledWarning(
          "hosting",
          `Your firebase.json contains custom routing rules (headers, redirects, or rewrites). ` +
            `These should be moved to your framework-native configuration file (e.g., next.config.js or angular.json). ` +
            `If not migrated, they will not be respected by App Hosting.`,
        );
        const confirmManualRules = await confirm({
          message: "Have you migrated these routing rules to your framework configuration?",
          default: false,
        });
        if (!confirmManualRules) {
          throw new FirebaseError(
            "Deployment cancelled. Please migrate routing rules and try again.",
          );
        }
      }

      // Prompt env vars
      logLabeledWarning(
        "hosting",
        "Any environment variables should be migrated to your apphosting.yaml file.",
      );
      const confirmEnv = await confirm({
        message: "Have you migrated your environment variables to apphosting.yaml?",
        default: false,
      });
      if (!confirmEnv) {
        throw new FirebaseError(
          "Deployment cancelled. Please migrate environment variables and try again.",
        );
      }

      logLabeledSuccess(
        "hosting",
        `Successfully migrated site "${site}" configuration to App Hosting.`,
      );
    } else {
      // Static / Flutter framework
      logLabeledWarning(
        "hosting",
        `Detected static framework: ${clc.bold(framework)}. Legacy 'webframeworks' experiment is deprecated for purely static apps.`,
      );

      if (options.nonInteractive) {
        logLabeledWarning(
          "hosting",
          "Running in non-interactive mode. Proceeding with legacy deployment (deprecated).",
        );
        updatedConfigs.push(config);
        continue;
      }

      const confirmStatic = await confirm({
        message: `Would you like to automatically migrate site "${site}" to standard Firebase Hosting? (This will configure a pre-deploy build hook and disable the experiment for this site)`,
        default: true,
      });

      if (!confirmStatic) {
        logLabeledWarning(
          "hosting",
          "Continuing with legacy deployment (deprecated). We strongly recommend migrating to standard Hosting.",
        );
        updatedConfigs.push(config);
        continue;
      }

      // Auto-fix config
      const newHostingConfig = { ...config };
      delete newHostingConfig.source;

      let buildCommand = "npm run build";
      let publicFolder = "dist";

      if (framework === "flutter") {
        buildCommand = "flutter build web";
        publicFolder = "build/web";
      } else {
        // Try to detect if there's package.json and build folder
        const packageJsonPath = join(getProjectPath(), "package.json");
        if (fs.existsSync(packageJsonPath)) {
          try {
            const pkg = fs.readJsonSync(packageJsonPath);
            if (pkg.scripts && pkg.scripts.build) {
              // Default to npm run build, or yarn build if yarn.lock exists
              if (fs.existsSync(join(getProjectPath(), "yarn.lock"))) {
                buildCommand = "yarn build";
              } else if (fs.existsSync(join(getProjectPath(), "pnpm-lock.yaml"))) {
                buildCommand = "pnpm build";
              }
            }
          } catch {
            // no-op
          }
        }
      }

      newHostingConfig.public = publicFolder;
      newHostingConfig.predeploy = buildCommand;
      updatedConfigs.push(newHostingConfig);

      logLabeledSuccess(
        "hosting",
        `Successfully migrated site "${site}" to standard Hosting with predeploy hook.`,
      );
    }
  }

  // Always write consolidated configs and save to disk!
  options.config.set(
    "hosting",
    Array.isArray(options.config.get("hosting")) ? updatedConfigs : updatedConfigs[0],
  );
  const configPath = join(projectRoot, "firebase.json");
  options.config.writeProjectFile(configPath, options.config.src);

  // Clear cached normalized config to force re-resolution!
  delete options.normalizedHostingConfig;

  if (hasSsrMigration) {
    // Swap deploy targets from hosting to apphosting!
    const index = targetNames.indexOf("hosting");
    if (index !== -1) {
      targetNames[index] = "apphosting";
      logLabeledBullet("hosting", `Shifting deploy target from Hosting to App Hosting.`);
    }
    // Ensure the apphostinglocalbuilds experiment is checked
    experiments.assertEnabled("apphostinglocalbuilds", "App Hosting local builds");
  }
}
