// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AccountSectionScssNamespace {
  export interface IAccountSectionScss {
    accountRow: string;
    accountRowIcon: string;
    accountRowLabel: string;
    accountRowProject: string;
  }
}

declare const AccountSectionScssModule: AccountSectionScssNamespace.IAccountSectionScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AccountSectionScssNamespace.IAccountSectionScss;
};

export = AccountSectionScssModule;
