# # Example mutations for a simple email app

# # Logged in user can create their own account.
# mutation CreateUser($name: String!, $address: String!) @auth(level: USER) {
#   # <type>_insert lets you create a new row in your table.
#   user_insert(data: {
#     # Server values let your service populate sensitive data.
#     # Users can only setup their own account.
#     uid_expr: "auth.uid",
#     name: $name,
#     address: $address
#   })
# }

# # Logged in user can send emails from their account.
# mutation CreateEmail($content: String, $subject: String) @auth(level: USER) {
#   email_insert(data: {
#     # The request variable name doesn't have to match the field name.
#     text: $content,
#     subject: $subject,
#     # Server values let your service populate sensitive data.
#     # Users are only allowed to create emails sent from their account.
#     fromUid_expr: "auth.uid",
#     # Server values let your service populate data for you
#     # Here, we use sent_date: { today: true } to set 'sent' to today's date.
#     sent_date: { today: true }
#   })
# }

# mutation CreateRecipient($emailId: UUID) @auth(level: USER) {
#   recipient_insert(data: {
#     emailId: $emailId,
#     userUid_expr: "auth.uid"
#   })
# }
