// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PanelSectionScssNamespace {
  export interface IPanelSectionScss {
    isExpanded: string;
    panelExpando: string;
    panelExpandoIcon: string;
  }
}

declare const PanelSectionScssModule: PanelSectionScssNamespace.IPanelSectionScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: PanelSectionScssNamespace.IPanelSectionScss;
};

export = PanelSectionScssModule;
