// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SpacerScssNamespace {
  export interface ISpacerScss {
    spacerlarge: string;
    spacermedium: string;
    spacersmall: string;
    spacerxlarge: string;
    spacerxsmall: string;
    spacerxxlarge: string;
  }
}

declare const SpacerScssModule: SpacerScssNamespace.ISpacerScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SpacerScssNamespace.ISpacerScss;
};

export = SpacerScssModule;
