// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TextScssNamespace {
  export interface ITextScss {
    b1: string;
    b2: string;
    colorSecondary: string;
    l1: string;
    l2: string;
    l3: string;
    l4: string;
    text: string;
  }
}

declare const TextScssModule: TextScssNamespace.ITextScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: TextScssNamespace.ITextScss;
};

export = TextScssModule;
