mutation createPost($data: Post_Data! @pick(fields: ["id", "content"]))
@auth(level: PUBLIC) {
  post_insert(data: $data)
}
mutation deletePost($id: String!) @auth(level: PUBLIC) {
  post_delete(id: $id)
}

mutation createComment(
  $data: Comment_Data! @pick(fields: ["content", "postId"])
) @auth(level: PUBLIC) {
  comment_insert(data: $data)
}
