require:
  - ts-node/register
  - source-map-support/register
  - src/test/helpers/mocha-bootstrap.ts
file:
  - src/test/helpers/global-mock-auth.ts
timeout: 5000
recursive: true
node-options:
  - no-experimental-strip-types
