steps:
  # Grab the latest version, store in workspace
  - id: "Read New Version Number from npm"
    name: "node"
    entrypoint: "sh"
    args:
      [
        "-c",
        "npm view firebase-tools version > /workspace/version_number.txt && cat /workspace/version_number.txt",
      ]
  # Publish the Firebase docker image
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "docker build -t us-docker.pkg.dev/$PROJECT_ID/us/firebase:$(cat /workspace/version_number.txt) -t us-docker.pkg.dev/$PROJECT_ID/us/firebase:latest -t us-docker.pkg.dev/$PROJECT_ID/us/firebase:public-image-$(cat /workspace/version_number.txt) -f ./Dockerfile ."

images:
  - "us-docker.pkg.dev/$PROJECT_ID/us/firebase"
