import { resolve } from "path";

/**
 * A sample JSON file for profiler input.
 */
export const SAMPLE_INPUT_PATH = resolve(import.meta.dirname, "sample.json");

/**
 * A sample JSON output file generated by the profiler.
 */
export const SAMPLE_OUTPUT_PATH = resolve(import.meta.dirname, "sample-output.json");
