blank_issues_enabled: false
contact_links:
  - name: 💻 Bug in the Emulator UI
    url: https://github.com/firebase/firebase-tools-ui/issues/new/choose
    about: Have you found a bug in the Emulator UI?
  - name: 🔥 Firebase Support
    url: https://firebase.google.com/support/
    about: If you have an urgent issue with your app in production, please contact support.
