"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.aitools = exports.apptestingAcutate = exports.apptestingAskQuestions = exports.genkit = exports.apphosting = exports.dataconnectSdkActuate = exports.dataconnectSdkAskQuestions = exports.dataconnectActuate = exports.dataconnectAskQuestions = exports.hostingGithub = exports.remoteconfig = exports.project = exports.extensions = exports.emulators = exports.storageActuate = exports.storageAskQuestions = exports.hosting = exports.functions = exports.firestoreActuate = exports.firestoreAskQuestions = exports.databaseActuate = exports.databaseAskQuestions = exports.account = void 0;
var account_1 = require("./account");
Object.defineProperty(exports, "account", { enumerable: true, get: function () { return account_1.doSetup; } });
var database_1 = require("./database");
Object.defineProperty(exports, "databaseAskQuestions", { enumerable: true, get: function () { return database_1.askQuestions; } });
Object.defineProperty(exports, "databaseActuate", { enumerable: true, get: function () { return database_1.actuate; } });
var firestore_1 = require("./firestore");
Object.defineProperty(exports, "firestoreAskQuestions", { enumerable: true, get: function () { return firestore_1.askQuestions; } });
Object.defineProperty(exports, "firestoreActuate", { enumerable: true, get: function () { return firestore_1.actuate; } });
var functions_1 = require("./functions");
Object.defineProperty(exports, "functions", { enumerable: true, get: function () { return functions_1.doSetup; } });
var hosting_1 = require("./hosting");
Object.defineProperty(exports, "hosting", { enumerable: true, get: function () { return hosting_1.doSetup; } });
var storage_1 = require("./storage");
Object.defineProperty(exports, "storageAskQuestions", { enumerable: true, get: function () { return storage_1.askQuestions; } });
Object.defineProperty(exports, "storageActuate", { enumerable: true, get: function () { return storage_1.actuate; } });
var emulators_1 = require("./emulators");
Object.defineProperty(exports, "emulators", { enumerable: true, get: function () { return emulators_1.doSetup; } });
var extensions_1 = require("./extensions");
Object.defineProperty(exports, "extensions", { enumerable: true, get: function () { return extensions_1.doSetup; } });
// always runs, sets up .firebaserc
var project_1 = require("./project");
Object.defineProperty(exports, "project", { enumerable: true, get: function () { return project_1.doSetup; } });
var remoteconfig_1 = require("./remoteconfig");
Object.defineProperty(exports, "remoteconfig", { enumerable: true, get: function () { return remoteconfig_1.doSetup; } });
var github_1 = require("./hosting/github");
Object.defineProperty(exports, "hostingGithub", { enumerable: true, get: function () { return github_1.initGitHub; } });
var dataconnect_1 = require("./dataconnect");
Object.defineProperty(exports, "dataconnectAskQuestions", { enumerable: true, get: function () { return dataconnect_1.askQuestions; } });
Object.defineProperty(exports, "dataconnectActuate", { enumerable: true, get: function () { return dataconnect_1.actuate; } });
var sdk_1 = require("./dataconnect/sdk");
Object.defineProperty(exports, "dataconnectSdkAskQuestions", { enumerable: true, get: function () { return sdk_1.askQuestions; } });
Object.defineProperty(exports, "dataconnectSdkActuate", { enumerable: true, get: function () { return sdk_1.actuate; } });
var apphosting_1 = require("./apphosting");
Object.defineProperty(exports, "apphosting", { enumerable: true, get: function () { return apphosting_1.doSetup; } });
var genkit_1 = require("./genkit");
Object.defineProperty(exports, "genkit", { enumerable: true, get: function () { return genkit_1.doSetup; } });
var apptesting_1 = require("./apptesting");
Object.defineProperty(exports, "apptestingAskQuestions", { enumerable: true, get: function () { return apptesting_1.askQuestions; } });
Object.defineProperty(exports, "apptestingAcutate", { enumerable: true, get: function () { return apptesting_1.actuate; } });
var aitools_1 = require("./aitools");
Object.defineProperty(exports, "aitools", { enumerable: true, get: function () { return aitools_1.doSetup; } });
//# sourceMappingURL=index.js.map