/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as clc from "colorette";
import { randomUUID } from "node:crypto";
import * as os from "os";

import { Command } from "../command";
import { needProjectNumber } from "../projectUtils";
import { createDebugToken, listDebugTokens, deleteDebugToken } from "../appcheck/api";
import { DebugToken, AppCheckDebugOptions } from "../appcheck/types";
import { getOrPromptProjectAndAppId } from "./appcheck-prompts";
import { requireAuth } from "../requireAuth";
import { promiseWithSpinner, logSuccess } from "../utils";
import { FirebaseError } from "../error";
import { confirm, input, password, select } from "../prompt";
import { logger } from "../logger";

export const command = new Command("appcheck:debugtokens:create [debugToken]")
  .description("generate and register an App Check debug token for an app")
  .option("--app <appId>", "the app id of your Firebase app")
  .option("--display-name <displayName>", "display name for the debug token")
  .option(
    "--force",
    "overwrite existing debug token if it has the same display name without prompting",
  )
  .before(requireAuth)
  .action(
    async (
      debugToken: string | undefined,
      options: AppCheckDebugOptions,
    ): Promise<DebugToken | void> => {
      const { appId } = await getOrPromptProjectAndAppId(options);

      const projectNumber = await needProjectNumber(options);

      let token = debugToken;
      if (!token) {
        if (!options.nonInteractive) {
          const action = await select({
            message:
              "Would you like to register a token generated by the SDK, or create a new one?",
            choices: [
              { name: "Create a new debug token", value: "generate" },
              { name: "Register a token generated by the SDK", value: "sdk" },
            ],
          });
          if (action === "sdk") {
            token = await password({
              message: "Enter the debug token generated by the SDK:",
              validate: (val) => (val.trim().length > 0 ? true : "Debug token cannot be empty."),
            });
          } else {
            token = randomUUID();
          }
        } else {
          token = randomUUID();
        }
      }

      let displayName = options.displayName;
      const defaultName = `CLI Debug Token (${os.hostname() || "Unknown Host"})`;
      if (!displayName) {
        if (!options.nonInteractive) {
          displayName = await input({
            message: "What would you like to call this debug token?",
            default: defaultName,
          });
        } else {
          displayName = defaultName;
        }
      }

      const existingTokens = await listDebugTokens(projectNumber, appId);
      const matchingTokens = existingTokens.filter((t) => t.displayName === displayName);

      if (matchingTokens.length > 0) {
        let shouldOverwrite = options.force;
        if (!shouldOverwrite) {
          if (options.nonInteractive) {
            throw new FirebaseError(
              `A token with the display name "${displayName}" already exists. Must pass --force to overwrite in non-interactive mode.`,
              { exit: 1 },
            );
          }
          shouldOverwrite = await confirm({
            message: `A token with the display name "${displayName}" already exists. Delete the old token(s)?`,
            default: true,
          });
        }
        if (shouldOverwrite) {
          for (const t of matchingTokens) {
            await deleteDebugToken(t.name);
          }
        } else {
          throw new FirebaseError("Registration canceled.", { exit: 1 });
        }
      }

      const result = await promiseWithSpinner<DebugToken>(
        async () => await createDebugToken(projectNumber, appId, displayName, token),
        `Registering App Check debug token with Firebase for app ${clc.bold(appId)}`,
      );

      logSuccess(`Successfully registered App Check debug token:
  - Display Name: ${clc.bold(result.displayName)}
  - Resource Name: ${clc.cyan(result.name)}`);

      if (!options.json) {
        console.log(`  - Token: ${clc.bold(clc.green(token))}\n`);
      }

      logger.info(
        clc.yellow(
          clc.bold("Warning: ") +
            "This debug token is a secret and should not be shared or uploaded to source code.",
        ),
      );
      logger.info(
        clc.yellow("TODO: Remember to delete this token once your testing has finished."),
      );

      return result;
    },
  );
