import * as sinon from "sinon";
import { expect } from "chai";
import { Command } from "../command";
import { command as apphostingBuildsCreate } from "./apphosting-builds-create";
import * as apphosting from "../gcp/apphosting";

describe("apphosting:builds:create", () => {
  const PROJECT_ID = "test-project";
  const BACKEND_ID = "test-backend";
  const LOCATION = "us-central1";

  let command: Command;
  let getNextRolloutIdStub: sinon.SinonStub;
  let createBuildStub: sinon.SinonStub;

  beforeEach(() => {
    command = apphostingBuildsCreate;
    command["befores"] = []; // Bypass pre-action hooks for unit testing action
    getNextRolloutIdStub = sinon.stub(apphosting, "getNextRolloutId").resolves("autogen-build-id");
    createBuildStub = sinon
      .stub(apphosting, "createBuild")
      .resolves({ name: "op-name" } as apphosting.Operation);
  });

  afterEach(() => {
    sinon.restore();
  });

  it("should not register -i short flag to avoid collision with global --interactive", () => {
    const options = command["options"] as string[][];
    const hasConflictingShortFlag = options.some((opt) => /(?:^|\s)-i\b/.test(opt[0]));
    expect(hasConflictingShortFlag).to.be.false;
  });

  it("should use autogenerated buildId when no id option is provided", async () => {
    const options = {
      project: PROJECT_ID,
    };

    await command.runner()(BACKEND_ID, options);

    expect(getNextRolloutIdStub).to.be.calledOnceWith(PROJECT_ID, LOCATION, BACKEND_ID);
    expect(createBuildStub).to.be.calledOnceWith(
      PROJECT_ID,
      LOCATION,
      BACKEND_ID,
      "autogen-build-id",
      {
        source: {
          codebase: {
            branch: "main",
          },
        },
      },
    );
  });

  it("should respect custom buildId passed via --id option", async () => {
    const options = {
      project: PROJECT_ID,
      id: "my-custom-build-id",
    };

    await command.runner()(BACKEND_ID, options);

    expect(getNextRolloutIdStub).to.not.be.called;
    expect(createBuildStub).to.be.calledOnceWith(
      PROJECT_ID,
      LOCATION,
      BACKEND_ID,
      "my-custom-build-id",
      {
        source: {
          codebase: {
            branch: "main",
          },
        },
      },
    );
  });

  it("should respect buildId passed via options.buildId", async () => {
    const options = {
      project: PROJECT_ID,
      buildId: "programmatic-build-id",
    };

    await command.runner()(BACKEND_ID, options);

    expect(getNextRolloutIdStub).to.not.be.called;
    expect(createBuildStub).to.be.calledOnceWith(
      PROJECT_ID,
      LOCATION,
      BACKEND_ID,
      "programmatic-build-id",
      {
        source: {
          codebase: {
            branch: "main",
          },
        },
      },
    );
  });
});
