extend type Query {
  """
  ✨ Look up a single `Order` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  order(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Order_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Order_FirstRow
  ): Order @fdc_generated(from: "Order", purpose: QUERY_SINGLE)
  """
  ✨ List `Order` objects in the table, optionally filtered by `where` conditions.
  """
  orders(
    """
    Filter condition to narrow down the query results.
    """
    where: Order_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Order_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100
  ): [Order!]! @fdc_generated(from: "Order", purpose: QUERY_MULTIPLE)
}
