// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SidebarEntryScssNamespace {
  export interface ISidebarEntryScss {
    fullWidth: string;
    hostingRow: string;
    hostingRowIcon: string;
    hostingRowLabel: string;
    hostingRowProject: string;
    hostingRowTest: string;
    integrationStatus: string;
    integrationStatusIcon: string;
    integrationStatusLabel: string;
    integrationStatusLoading: string;
  }
}

declare const SidebarEntryScssModule: SidebarEntryScssNamespace.ISidebarEntryScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SidebarEntryScssNamespace.ISidebarEntryScss;
};

export = SidebarEntryScssModule;
