export const pathsWithRegex = [
  "/(.*)",
  "/post/:slug(\\d{1,})",
  "/api-hello-regex/:first(.*)",
  "/unnamed-params/nested/(.*)/:test/(.*)",
  "/:path((?!another-page$).*)",
] as const;

export const pathsWithEscapedChars = [
  `/post\\(someStringBetweenParentheses\\)/:slug`,
  `/english\\(default\\)/:slug`,
] as const;

export const pathsWithRegexAndEscapedChars = [
  `/post/\\(escapedparentheses\\)/:slug(\\d{1,})`,
  `/post/\\(es\\?cap\\Wed\\*p\\{ar\\}en\\:th\\eses\\)`,
  `/post/\\(es\\?cap\\Wed\\*p\\{ar\\}en\\:th\\eses\\)/:slug(\\d{1,})`,
] as const;

export const pathsAsGlobs = [
  "/specific/:path*",
  "/another/:path*",
  "/about",
  "/",
  "/old-blog/:path*",
  "/blog/:path*",
  "/to-websocket",
  "/to-nowhere",
  "/rewriting-to-auto-export",
  "/rewriting-to-another-auto-export/:path*",
  "/to-another",
  "/another/one",
  "/nav",
  "/404",
  "/hello-world",
  "/static/hello.txt",
  "/another",
  "/multi-rewrites",
  "/first",
  "/hello",
  "/second",
  "/hello-again",
  "/to-hello",
  "/hello",
  "/blog/post-1",
  "/blog/post-2",
  "/test/:path",
  "/:path",
  "/test-overwrite/:something/:another",
  "/params/this-should-be-the-value",
  "/params/:something",
  "/with-params",
  "/query-rewrite/:section/:name",
  "/hidden/_next/:path*",
  "/_next/:path*",
  "/proxy-me/:path*",
  "/api-hello",
  "/api/hello",
  "/api-hello-param/:name",
  "/api-dynamic-param/:name",
  "/api/hello?name=:first*",
  "/api/hello?hello=:name",
  "/api/dynamic/:name?hello=:name",
  "/:path/post-321",
  "/with-params",
  "/with-params",
  "/catchall-rewrite/:path*",
  "/with-params",
  "/catchall-query/:path*",
  "/has-rewrite-1",
  "/has-rewrite-2",
  "/has-rewrite-3",
  "/has-rewrite-4",
  "/has-rewrite-5",
  "/:hasParam",
  "/has-rewrite-6",
  "/with-params",
  "/has-rewrite-7",
  "/has-rewrite-8",
  "/blog-catchall/:post",
  "/missing-rewrite-1",
  "/with-params",
  "/missing-rewrite-2",
  "/with-params",
  "/missing-rewrite-3",
  "/overridden/:path*",
] as const;

export const supportedPaths = [
  ...pathsWithEscapedChars,
  ...pathsAsGlobs,
  ...pathsWithRegex,
  ...pathsWithRegexAndEscapedChars,
] as const;

// It seems as though we support all these!
export const unsupportedPaths = [] as const;
