name: Functions deploy test

# Allow workflow to be triggered manually.
#   https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
on:
  workflow_dispatch:
#  schedule:
#    # Run the action every 2 hours.
#    # * is a special character in YAML so you have to quote this string
#    - cron: "0 */2 * * *"

permissions:
  contents: read

concurrency:
  # Limit at most 1 runs
  group: functions-deploy-${{ github.ref }}

env:
  CI: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
        with:
          # Ignored since the GITHUB_TOKEN needs to be persisted for this workflow.
          persist-credentials: true # zizmor: ignore[artipacked]
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # ratchet:actions/setup-node@v3
        with:
          node-version: "24"

      - uses: google-github-actions/auth@09cecabe1f169596b81c2ef22b40faff87acc460 # ratchet:google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.CF3_INTEGRATION_TEST_GOOGLE_CREDENTIALS }}"
          create_credentials_file: true

      - run: npm ci

      - name: "Test function deploy"
        run: npm run test:functions-deploy

      - name: Print debug logs
        if: failure()
        run: find . -type f -name "*debug.log" | xargs cat
